// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cubevs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type localgwIngressSession struct {
	Version  uint32
	VmIp     uint32
	VmPort   uint16
	Reserved [3]uint16
}

type localgwLpmKey struct {
	Prefixlen uint32
	Ip        uint32
}

type localgwMvmMeta struct {
	Version  uint32
	Ip       uint32
	Uuid     [64]uint8
	Reserved [56]uint8
}

type localgwMvmPort struct {
	Ifindex    uint32
	ListenPort uint16
	Reserved   uint16
}

type localgwNatSession struct {
	AccessTime  uint64
	NodeIfindex uint32
	NodeIp      uint32
	VmIfindex   uint32
	VmIp        uint32
	NodePort    uint16
	VmPort      uint16
	State       uint8
	ActiveClose uint8
	Reserved    [34]uint8
}

type localgwSessionKey struct {
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Version  uint32
	Protocol uint8
	Reserved [3]uint8
}

type localgwSnatIp struct {
	Lock     struct{ Val uint32 }
	Ifindex  uint32
	Ip       uint32
	MaxPort  uint16
	Reserved uint16
}

// loadLocalgw returns the embedded CollectionSpec for localgw.
func loadLocalgw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LocalgwBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load localgw: %w", err)
	}

	return spec, err
}

// loadLocalgwObjects loads localgw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*localgwObjects
//	*localgwPrograms
//	*localgwMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLocalgwObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLocalgw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// localgwSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type localgwSpecs struct {
	localgwProgramSpecs
	localgwMapSpecs
	localgwVariableSpecs
}

// localgwProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type localgwProgramSpecs struct {
	FromEnvoy *ebpf.ProgramSpec `ebpf:"from_envoy"`
}

// localgwMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type localgwMapSpecs struct {
	AllowOut          *ebpf.MapSpec `ebpf:"allow_out"`
	DenyOut           *ebpf.MapSpec `ebpf:"deny_out"`
	EgressSessions    *ebpf.MapSpec `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.MapSpec `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.MapSpec `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.MapSpec `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.MapSpec `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.MapSpec `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.MapSpec `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.MapSpec `ebpf:"snat_iplist"`
}

// localgwVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type localgwVariableSpecs struct {
	Cubegw0Ifindex   *ebpf.VariableSpec `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.VariableSpec `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.VariableSpec `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.VariableSpec `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.VariableSpec `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.VariableSpec `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.VariableSpec `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.VariableSpec `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.VariableSpec `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.VariableSpec `ebpf:"nodenic_macaddr_p2"`
}

// localgwObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLocalgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type localgwObjects struct {
	localgwPrograms
	localgwMaps
	localgwVariables
}

func (o *localgwObjects) Close() error {
	return _LocalgwClose(
		&o.localgwPrograms,
		&o.localgwMaps,
	)
}

// localgwMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLocalgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type localgwMaps struct {
	AllowOut          *ebpf.Map `ebpf:"allow_out"`
	DenyOut           *ebpf.Map `ebpf:"deny_out"`
	EgressSessions    *ebpf.Map `ebpf:"egress_sessions"`
	IfindexToMvmmeta  *ebpf.Map `ebpf:"ifindex_to_mvmmeta"`
	IngressSessions   *ebpf.Map `ebpf:"ingress_sessions"`
	LocalPortMapping  *ebpf.Map `ebpf:"local_port_mapping"`
	MvmipToIfindex    *ebpf.Map `ebpf:"mvmip_to_ifindex"`
	NetPolicyInner    *ebpf.Map `ebpf:"net_policy_inner"`
	RemotePortMapping *ebpf.Map `ebpf:"remote_port_mapping"`
	SnatIplist        *ebpf.Map `ebpf:"snat_iplist"`
}

func (m *localgwMaps) Close() error {
	return _LocalgwClose(
		m.AllowOut,
		m.DenyOut,
		m.EgressSessions,
		m.IfindexToMvmmeta,
		m.IngressSessions,
		m.LocalPortMapping,
		m.MvmipToIfindex,
		m.NetPolicyInner,
		m.RemotePortMapping,
		m.SnatIplist,
	)
}

// localgwVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLocalgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type localgwVariables struct {
	Cubegw0Ifindex   *ebpf.Variable `ebpf:"cubegw0_ifindex"`
	Cubegw0Ip        *ebpf.Variable `ebpf:"cubegw0_ip"`
	Cubegw0MacaddrP1 *ebpf.Variable `ebpf:"cubegw0_macaddr_p1"`
	Cubegw0MacaddrP2 *ebpf.Variable `ebpf:"cubegw0_macaddr_p2"`
	MvmGatewayIp     *ebpf.Variable `ebpf:"mvm_gateway_ip"`
	MvmInnerIp       *ebpf.Variable `ebpf:"mvm_inner_ip"`
	MvmMacaddrP1     *ebpf.Variable `ebpf:"mvm_macaddr_p1"`
	MvmMacaddrP2     *ebpf.Variable `ebpf:"mvm_macaddr_p2"`
	NodegwMacaddrP1  *ebpf.Variable `ebpf:"nodegw_macaddr_p1"`
	NodegwMacaddrP2  *ebpf.Variable `ebpf:"nodegw_macaddr_p2"`
	NodenicIfindex   *ebpf.Variable `ebpf:"nodenic_ifindex"`
	NodenicIp        *ebpf.Variable `ebpf:"nodenic_ip"`
	NodenicMacaddrP1 *ebpf.Variable `ebpf:"nodenic_macaddr_p1"`
	NodenicMacaddrP2 *ebpf.Variable `ebpf:"nodenic_macaddr_p2"`
}

// localgwPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLocalgwObjects or ebpf.CollectionSpec.LoadAndAssign.
type localgwPrograms struct {
	FromEnvoy *ebpf.Program `ebpf:"from_envoy"`
}

func (p *localgwPrograms) Close() error {
	return _LocalgwClose(
		p.FromEnvoy,
	)
}

func _LocalgwClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed localgw_x86_bpfel.o
var _LocalgwBytes []byte
