// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/cubebox/v1/cubebox.proto

package cubebox

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CubeboxMgr_Create_FullMethodName          = "/cubelet.services.cubebox.v1.CubeboxMgr/Create"
	CubeboxMgr_Destroy_FullMethodName         = "/cubelet.services.cubebox.v1.CubeboxMgr/Destroy"
	CubeboxMgr_List_FullMethodName            = "/cubelet.services.cubebox.v1.CubeboxMgr/List"
	CubeboxMgr_Update_FullMethodName          = "/cubelet.services.cubebox.v1.CubeboxMgr/Update"
	CubeboxMgr_Exec_FullMethodName            = "/cubelet.services.cubebox.v1.CubeboxMgr/Exec"
	CubeboxMgr_AppSnapshot_FullMethodName     = "/cubelet.services.cubebox.v1.CubeboxMgr/AppSnapshot"
	CubeboxMgr_CommitSandbox_FullMethodName   = "/cubelet.services.cubebox.v1.CubeboxMgr/CommitSandbox"
	CubeboxMgr_CleanupTemplate_FullMethodName = "/cubelet.services.cubebox.v1.CubeboxMgr/CleanupTemplate"
)

// CubeboxMgrClient is the client API for CubeboxMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for handling cubesandbox
type CubeboxMgrClient interface {
	Create(ctx context.Context, in *RunCubeSandboxRequest, opts ...grpc.CallOption) (*RunCubeSandboxResponse, error)
	Destroy(ctx context.Context, in *DestroyCubeSandboxRequest, opts ...grpc.CallOption) (*DestroyCubeSandboxResponse, error)
	List(ctx context.Context, in *ListCubeSandboxRequest, opts ...grpc.CallOption) (*ListCubeSandboxResponse, error)
	Update(ctx context.Context, in *UpdateCubeSandboxRequest, opts ...grpc.CallOption) (*UpdateCubeSandboxResponse, error)
	Exec(ctx context.Context, in *ExecCubeSandboxRequest, opts ...grpc.CallOption) (*ExecCubeSandboxResponse, error)
	// AppSnapshot creates a cubebox, makes an app snapshot, and destroys the cubebox.
	// Required annotations:
	//   - cube.master.appsnapshot.create: "true"
	//   - cube.master.appsnapshot.template.id: "<template_id>"
	AppSnapshot(ctx context.Context, in *AppSnapshotRequest, opts ...grpc.CallOption) (*AppSnapshotResponse, error)
	// CommitSandbox snapshots an existing running sandbox into a template snapshot.
	CommitSandbox(ctx context.Context, in *CommitSandboxRequest, opts ...grpc.CallOption) (*CommitSandboxResponse, error)
	// CleanupTemplate removes local template snapshot/base data from this node.
	CleanupTemplate(ctx context.Context, in *CleanupTemplateRequest, opts ...grpc.CallOption) (*CleanupTemplateResponse, error)
}

type cubeboxMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeboxMgrClient(cc grpc.ClientConnInterface) CubeboxMgrClient {
	return &cubeboxMgrClient{cc}
}

func (c *cubeboxMgrClient) Create(ctx context.Context, in *RunCubeSandboxRequest, opts ...grpc.CallOption) (*RunCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Destroy(ctx context.Context, in *DestroyCubeSandboxRequest, opts ...grpc.CallOption) (*DestroyCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) List(ctx context.Context, in *ListCubeSandboxRequest, opts ...grpc.CallOption) (*ListCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Update(ctx context.Context, in *UpdateCubeSandboxRequest, opts ...grpc.CallOption) (*UpdateCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) Exec(ctx context.Context, in *ExecCubeSandboxRequest, opts ...grpc.CallOption) (*ExecCubeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecCubeSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) AppSnapshot(ctx context.Context, in *AppSnapshotRequest, opts ...grpc.CallOption) (*AppSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSnapshotResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_AppSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) CommitSandbox(ctx context.Context, in *CommitSandboxRequest, opts ...grpc.CallOption) (*CommitSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitSandboxResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_CommitSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeboxMgrClient) CleanupTemplate(ctx context.Context, in *CleanupTemplateRequest, opts ...grpc.CallOption) (*CleanupTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupTemplateResponse)
	err := c.cc.Invoke(ctx, CubeboxMgr_CleanupTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeboxMgrServer is the server API for CubeboxMgr service.
// All implementations must embed UnimplementedCubeboxMgrServer
// for forward compatibility.
//
// Service for handling cubesandbox
type CubeboxMgrServer interface {
	Create(context.Context, *RunCubeSandboxRequest) (*RunCubeSandboxResponse, error)
	Destroy(context.Context, *DestroyCubeSandboxRequest) (*DestroyCubeSandboxResponse, error)
	List(context.Context, *ListCubeSandboxRequest) (*ListCubeSandboxResponse, error)
	Update(context.Context, *UpdateCubeSandboxRequest) (*UpdateCubeSandboxResponse, error)
	Exec(context.Context, *ExecCubeSandboxRequest) (*ExecCubeSandboxResponse, error)
	// AppSnapshot creates a cubebox, makes an app snapshot, and destroys the cubebox.
	// Required annotations:
	//   - cube.master.appsnapshot.create: "true"
	//   - cube.master.appsnapshot.template.id: "<template_id>"
	AppSnapshot(context.Context, *AppSnapshotRequest) (*AppSnapshotResponse, error)
	// CommitSandbox snapshots an existing running sandbox into a template snapshot.
	CommitSandbox(context.Context, *CommitSandboxRequest) (*CommitSandboxResponse, error)
	// CleanupTemplate removes local template snapshot/base data from this node.
	CleanupTemplate(context.Context, *CleanupTemplateRequest) (*CleanupTemplateResponse, error)
	mustEmbedUnimplementedCubeboxMgrServer()
}

// UnimplementedCubeboxMgrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeboxMgrServer struct{}

func (UnimplementedCubeboxMgrServer) Create(context.Context, *RunCubeSandboxRequest) (*RunCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCubeboxMgrServer) Destroy(context.Context, *DestroyCubeSandboxRequest) (*DestroyCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedCubeboxMgrServer) List(context.Context, *ListCubeSandboxRequest) (*ListCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCubeboxMgrServer) Update(context.Context, *UpdateCubeSandboxRequest) (*UpdateCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCubeboxMgrServer) Exec(context.Context, *ExecCubeSandboxRequest) (*ExecCubeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedCubeboxMgrServer) AppSnapshot(context.Context, *AppSnapshotRequest) (*AppSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppSnapshot not implemented")
}
func (UnimplementedCubeboxMgrServer) CommitSandbox(context.Context, *CommitSandboxRequest) (*CommitSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitSandbox not implemented")
}
func (UnimplementedCubeboxMgrServer) CleanupTemplate(context.Context, *CleanupTemplateRequest) (*CleanupTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupTemplate not implemented")
}
func (UnimplementedCubeboxMgrServer) mustEmbedUnimplementedCubeboxMgrServer() {}
func (UnimplementedCubeboxMgrServer) testEmbeddedByValue()                    {}

// UnsafeCubeboxMgrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeboxMgrServer will
// result in compilation errors.
type UnsafeCubeboxMgrServer interface {
	mustEmbedUnimplementedCubeboxMgrServer()
}

func RegisterCubeboxMgrServer(s grpc.ServiceRegistrar, srv CubeboxMgrServer) {
	// If the following call panics, it indicates UnimplementedCubeboxMgrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeboxMgr_ServiceDesc, srv)
}

func _CubeboxMgr_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Create(ctx, req.(*RunCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Destroy(ctx, req.(*DestroyCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).List(ctx, req.(*ListCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Update(ctx, req.(*UpdateCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCubeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).Exec(ctx, req.(*ExecCubeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_AppSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).AppSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_AppSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).AppSnapshot(ctx, req.(*AppSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_CommitSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).CommitSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_CommitSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).CommitSandbox(ctx, req.(*CommitSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeboxMgr_CleanupTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeboxMgrServer).CleanupTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeboxMgr_CleanupTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeboxMgrServer).CleanupTemplate(ctx, req.(*CleanupTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeboxMgr_ServiceDesc is the grpc.ServiceDesc for CubeboxMgr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeboxMgr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.v1.CubeboxMgr",
	HandlerType: (*CubeboxMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CubeboxMgr_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _CubeboxMgr_Destroy_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CubeboxMgr_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CubeboxMgr_Update_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _CubeboxMgr_Exec_Handler,
		},
		{
			MethodName: "AppSnapshot",
			Handler:    _CubeboxMgr_AppSnapshot_Handler,
		},
		{
			MethodName: "CommitSandbox",
			Handler:    _CubeboxMgr_CommitSandbox_Handler,
		},
		{
			MethodName: "CleanupTemplate",
			Handler:    _CubeboxMgr_CleanupTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/cubebox/v1/cubebox.proto",
}
