// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.2
// source: Cubelet/pkg/networkagentclient/pb/network_agent.proto

package networkagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureNetworkRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Interfaces      []*Interface           `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes          []*Route               `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	ArpNeighbors    []*ARPNeighbor         `protobuf:"bytes,5,rep,name=arp_neighbors,json=arpNeighbors,proto3" json:"arp_neighbors,omitempty"`
	PortMappings    []*PortMapping         `protobuf:"bytes,6,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,7,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CubevsContext   *CubeVSContext         `protobuf:"bytes,8,opt,name=cubevs_context,json=cubevsContext,proto3,oneof" json:"cubevs_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnsureNetworkRequest) Reset() {
	*x = EnsureNetworkRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureNetworkRequest) ProtoMessage() {}

func (x *EnsureNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureNetworkRequest.ProtoReflect.Descriptor instead.
func (*EnsureNetworkRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureNetworkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *EnsureNetworkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EnsureNetworkRequest) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *EnsureNetworkRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *EnsureNetworkRequest) GetArpNeighbors() []*ARPNeighbor {
	if x != nil {
		return x.ArpNeighbors
	}
	return nil
}

func (x *EnsureNetworkRequest) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *EnsureNetworkRequest) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

func (x *EnsureNetworkRequest) GetCubevsContext() *CubeVSContext {
	if x != nil {
		return x.CubevsContext
	}
	return nil
}

type EnsureNetworkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle   string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	Interfaces      []*Interface           `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes          []*Route               `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	ArpNeighbors    []*ARPNeighbor         `protobuf:"bytes,5,rep,name=arp_neighbors,json=arpNeighbors,proto3" json:"arp_neighbors,omitempty"`
	PortMappings    []*PortMapping         `protobuf:"bytes,6,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,7,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnsureNetworkResponse) Reset() {
	*x = EnsureNetworkResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureNetworkResponse) ProtoMessage() {}

func (x *EnsureNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureNetworkResponse.ProtoReflect.Descriptor instead.
func (*EnsureNetworkResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureNetworkResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *EnsureNetworkResponse) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *EnsureNetworkResponse) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *EnsureNetworkResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *EnsureNetworkResponse) GetArpNeighbors() []*ARPNeighbor {
	if x != nil {
		return x.ArpNeighbors
	}
	return nil
}

func (x *EnsureNetworkResponse) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *EnsureNetworkResponse) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

type ReleaseNetworkRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle   string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,4,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReleaseNetworkRequest) Reset() {
	*x = ReleaseNetworkRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseNetworkRequest) ProtoMessage() {}

func (x *ReleaseNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseNetworkRequest.ProtoReflect.Descriptor instead.
func (*ReleaseNetworkRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseNetworkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReleaseNetworkRequest) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *ReleaseNetworkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReleaseNetworkRequest) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

type ReleaseNetworkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Released        bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,2,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReleaseNetworkResponse) Reset() {
	*x = ReleaseNetworkResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseNetworkResponse) ProtoMessage() {}

func (x *ReleaseNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseNetworkResponse.ProtoReflect.Descriptor instead.
func (*ReleaseNetworkResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseNetworkResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseNetworkResponse) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

type ReconcileNetworkRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle   string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Interfaces      []*Interface           `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes          []*Route               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	ArpNeighbors    []*ARPNeighbor         `protobuf:"bytes,6,rep,name=arp_neighbors,json=arpNeighbors,proto3" json:"arp_neighbors,omitempty"`
	PortMappings    []*PortMapping         `protobuf:"bytes,7,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,8,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CubevsContext   *CubeVSContext         `protobuf:"bytes,9,opt,name=cubevs_context,json=cubevsContext,proto3,oneof" json:"cubevs_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReconcileNetworkRequest) Reset() {
	*x = ReconcileNetworkRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileNetworkRequest) ProtoMessage() {}

func (x *ReconcileNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileNetworkRequest.ProtoReflect.Descriptor instead.
func (*ReconcileNetworkRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReconcileNetworkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReconcileNetworkRequest) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *ReconcileNetworkRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReconcileNetworkRequest) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *ReconcileNetworkRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ReconcileNetworkRequest) GetArpNeighbors() []*ARPNeighbor {
	if x != nil {
		return x.ArpNeighbors
	}
	return nil
}

func (x *ReconcileNetworkRequest) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *ReconcileNetworkRequest) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

func (x *ReconcileNetworkRequest) GetCubevsContext() *CubeVSContext {
	if x != nil {
		return x.CubevsContext
	}
	return nil
}

type ReconcileNetworkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle   string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	Converged       bool                   `protobuf:"varint,3,opt,name=converged,proto3" json:"converged,omitempty"`
	Interfaces      []*Interface           `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes          []*Route               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	ArpNeighbors    []*ARPNeighbor         `protobuf:"bytes,6,rep,name=arp_neighbors,json=arpNeighbors,proto3" json:"arp_neighbors,omitempty"`
	PortMappings    []*PortMapping         `protobuf:"bytes,7,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,8,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReconcileNetworkResponse) Reset() {
	*x = ReconcileNetworkResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileNetworkResponse) ProtoMessage() {}

func (x *ReconcileNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileNetworkResponse.ProtoReflect.Descriptor instead.
func (*ReconcileNetworkResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ReconcileNetworkResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReconcileNetworkResponse) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *ReconcileNetworkResponse) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

func (x *ReconcileNetworkResponse) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *ReconcileNetworkResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ReconcileNetworkResponse) GetArpNeighbors() []*ARPNeighbor {
	if x != nil {
		return x.ArpNeighbors
	}
	return nil
}

func (x *ReconcileNetworkResponse) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *ReconcileNetworkResponse) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetNetworkRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *GetNetworkRequest) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

type GetNetworkResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SandboxId       string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle   string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	Interfaces      []*Interface           `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Routes          []*Route               `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	ArpNeighbors    []*ARPNeighbor         `protobuf:"bytes,5,rep,name=arp_neighbors,json=arpNeighbors,proto3" json:"arp_neighbors,omitempty"`
	PortMappings    []*PortMapping         `protobuf:"bytes,6,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	PersistMetadata map[string]string      `protobuf:"bytes,7,rep,name=persist_metadata,json=persistMetadata,proto3" json:"persist_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetNetworkResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *GetNetworkResponse) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *GetNetworkResponse) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *GetNetworkResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetNetworkResponse) GetArpNeighbors() []*ARPNeighbor {
	if x != nil {
		return x.ArpNeighbors
	}
	return nil
}

func (x *GetNetworkResponse) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *GetNetworkResponse) GetPersistMetadata() map[string]string {
	if x != nil {
		return x.PersistMetadata
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HealthRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksRequest) Reset() {
	*x = ListNetworksRequest{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksRequest) ProtoMessage() {}

func (x *ListNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{10}
}

type ListNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*NetworkState        `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksResponse) Reset() {
	*x = ListNetworksResponse{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksResponse) ProtoMessage() {}

func (x *ListNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListNetworksResponse) GetNetworks() []*NetworkState {
	if x != nil {
		return x.Networks
	}
	return nil
}

type NetworkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	NetworkHandle string                 `protobuf:"bytes,2,opt,name=network_handle,json=networkHandle,proto3" json:"network_handle,omitempty"`
	TapName       string                 `protobuf:"bytes,3,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	TapIfindex    int32                  `protobuf:"varint,4,opt,name=tap_ifindex,json=tapIfindex,proto3" json:"tap_ifindex,omitempty"`
	SandboxIp     string                 `protobuf:"bytes,5,opt,name=sandbox_ip,json=sandboxIp,proto3" json:"sandbox_ip,omitempty"`
	PortMappings  []*PortMapping         `protobuf:"bytes,6,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkState) Reset() {
	*x = NetworkState{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkState) ProtoMessage() {}

func (x *NetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkState.ProtoReflect.Descriptor instead.
func (*NetworkState) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkState) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *NetworkState) GetNetworkHandle() string {
	if x != nil {
		return x.NetworkHandle
	}
	return ""
}

func (x *NetworkState) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

func (x *NetworkState) GetTapIfindex() int32 {
	if x != nil {
		return x.TapIfindex
	}
	return 0
}

func (x *NetworkState) GetSandboxIp() string {
	if x != nil {
		return x.SandboxIp
	}
	return ""
}

func (x *NetworkState) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	HostPort      uint32                 `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	HostIp        string                 `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{13}
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortMapping) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpCidrs       []string               `protobuf:"bytes,3,rep,name=ip_cidrs,json=ipCidrs,proto3" json:"ip_cidrs,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Mtu           int32                  `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Interface) GetIpCidrs() []string {
	if x != nil {
		return x.IpCidrs
	}
	return nil
}

func (x *Interface) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Interface) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type Route struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestinationCidr string                 `protobuf:"bytes,1,opt,name=destination_cidr,json=destinationCidr,proto3" json:"destination_cidr,omitempty"`
	Gateway         string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Device          string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{15}
}

func (x *Route) GetDestinationCidr() string {
	if x != nil {
		return x.DestinationCidr
	}
	return ""
}

func (x *Route) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Route) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ARPNeighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARPNeighbor) Reset() {
	*x = ARPNeighbor{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARPNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARPNeighbor) ProtoMessage() {}

func (x *ARPNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARPNeighbor.ProtoReflect.Descriptor instead.
func (*ARPNeighbor) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ARPNeighbor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ARPNeighbor) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ARPNeighbor) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type CubeVSContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AllowInternetAccess *bool                  `protobuf:"varint,1,opt,name=allow_internet_access,json=allowInternetAccess,proto3,oneof" json:"allow_internet_access,omitempty"`
	AllowOut            []string               `protobuf:"bytes,2,rep,name=allow_out,json=allowOut,proto3" json:"allow_out,omitempty"`
	DenyOut             []string               `protobuf:"bytes,3,rep,name=deny_out,json=denyOut,proto3" json:"deny_out,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CubeVSContext) Reset() {
	*x = CubeVSContext{}
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeVSContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeVSContext) ProtoMessage() {}

func (x *CubeVSContext) ProtoReflect() protoreflect.Message {
	mi := &file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeVSContext.ProtoReflect.Descriptor instead.
func (*CubeVSContext) Descriptor() ([]byte, []int) {
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CubeVSContext) GetAllowInternetAccess() bool {
	if x != nil && x.AllowInternetAccess != nil {
		return *x.AllowInternetAccess
	}
	return false
}

func (x *CubeVSContext) GetAllowOut() []string {
	if x != nil {
		return x.AllowOut
	}
	return nil
}

func (x *CubeVSContext) GetDenyOut() []string {
	if x != nil {
		return x.DenyOut
	}
	return nil
}

var File_Cubelet_pkg_networkagentclient_pb_network_agent_proto protoreflect.FileDescriptor

const file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDesc = "" +
	"\n" +
	"5Cubelet/pkg/networkagentclient/pb/network_agent.proto\x12\x14network_agent.api.v1\"\xf8\x04\n" +
	"\x14EnsureNetworkRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12?\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1f.network_agent.api.v1.InterfaceR\n" +
	"interfaces\x123\n" +
	"\x06routes\x18\x04 \x03(\v2\x1b.network_agent.api.v1.RouteR\x06routes\x12F\n" +
	"\rarp_neighbors\x18\x05 \x03(\v2!.network_agent.api.v1.ARPNeighborR\farpNeighbors\x12F\n" +
	"\rport_mappings\x18\x06 \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\x12j\n" +
	"\x10persist_metadata\x18\a \x03(\v2?.network_agent.api.v1.EnsureNetworkRequest.PersistMetadataEntryR\x0fpersistMetadata\x12O\n" +
	"\x0ecubevs_context\x18\b \x01(\v2#.network_agent.api.v1.CubeVSContextH\x00R\rcubevsContext\x88\x01\x01\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_cubevs_context\"\x94\x04\n" +
	"\x15EnsureNetworkResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12?\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1f.network_agent.api.v1.InterfaceR\n" +
	"interfaces\x123\n" +
	"\x06routes\x18\x04 \x03(\v2\x1b.network_agent.api.v1.RouteR\x06routes\x12F\n" +
	"\rarp_neighbors\x18\x05 \x03(\v2!.network_agent.api.v1.ARPNeighborR\farpNeighbors\x12F\n" +
	"\rport_mappings\x18\x06 \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\x12k\n" +
	"\x10persist_metadata\x18\a \x03(\v2@.network_agent.api.v1.EnsureNetworkResponse.PersistMetadataEntryR\x0fpersistMetadata\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x02\n" +
	"\x15ReleaseNetworkRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12k\n" +
	"\x10persist_metadata\x18\x04 \x03(\v2@.network_agent.api.v1.ReleaseNetworkRequest.PersistMetadataEntryR\x0fpersistMetadata\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x16ReleaseNetworkResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12l\n" +
	"\x10persist_metadata\x18\x02 \x03(\v2A.network_agent.api.v1.ReleaseNetworkResponse.PersistMetadataEntryR\x0fpersistMetadata\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x05\n" +
	"\x17ReconcileNetworkRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12?\n" +
	"\n" +
	"interfaces\x18\x04 \x03(\v2\x1f.network_agent.api.v1.InterfaceR\n" +
	"interfaces\x123\n" +
	"\x06routes\x18\x05 \x03(\v2\x1b.network_agent.api.v1.RouteR\x06routes\x12F\n" +
	"\rarp_neighbors\x18\x06 \x03(\v2!.network_agent.api.v1.ARPNeighborR\farpNeighbors\x12F\n" +
	"\rport_mappings\x18\a \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\x12m\n" +
	"\x10persist_metadata\x18\b \x03(\v2B.network_agent.api.v1.ReconcileNetworkRequest.PersistMetadataEntryR\x0fpersistMetadata\x12O\n" +
	"\x0ecubevs_context\x18\t \x01(\v2#.network_agent.api.v1.CubeVSContextH\x00R\rcubevsContext\x88\x01\x01\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_cubevs_context\"\xb8\x04\n" +
	"\x18ReconcileNetworkResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12\x1c\n" +
	"\tconverged\x18\x03 \x01(\bR\tconverged\x12?\n" +
	"\n" +
	"interfaces\x18\x04 \x03(\v2\x1f.network_agent.api.v1.InterfaceR\n" +
	"interfaces\x123\n" +
	"\x06routes\x18\x05 \x03(\v2\x1b.network_agent.api.v1.RouteR\x06routes\x12F\n" +
	"\rarp_neighbors\x18\x06 \x03(\v2!.network_agent.api.v1.ARPNeighborR\farpNeighbors\x12F\n" +
	"\rport_mappings\x18\a \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\x12n\n" +
	"\x10persist_metadata\x18\b \x03(\v2C.network_agent.api.v1.ReconcileNetworkResponse.PersistMetadataEntryR\x0fpersistMetadata\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x11GetNetworkRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\"\x8e\x04\n" +
	"\x12GetNetworkResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12?\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1f.network_agent.api.v1.InterfaceR\n" +
	"interfaces\x123\n" +
	"\x06routes\x18\x04 \x03(\v2\x1b.network_agent.api.v1.RouteR\x06routes\x12F\n" +
	"\rarp_neighbors\x18\x05 \x03(\v2!.network_agent.api.v1.ARPNeighborR\farpNeighbors\x12F\n" +
	"\rport_mappings\x18\x06 \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\x12h\n" +
	"\x10persist_metadata\x18\a \x03(\v2=.network_agent.api.v1.GetNetworkResponse.PersistMetadataEntryR\x0fpersistMetadata\x1aB\n" +
	"\x14PersistMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\rHealthRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"8\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x15\n" +
	"\x13ListNetworksRequest\"V\n" +
	"\x14ListNetworksResponse\x12>\n" +
	"\bnetworks\x18\x01 \x03(\v2\".network_agent.api.v1.NetworkStateR\bnetworks\"\xf7\x01\n" +
	"\fNetworkState\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0enetwork_handle\x18\x02 \x01(\tR\rnetworkHandle\x12\x19\n" +
	"\btap_name\x18\x03 \x01(\tR\atapName\x12\x1f\n" +
	"\vtap_ifindex\x18\x04 \x01(\x05R\n" +
	"tapIfindex\x12\x1d\n" +
	"\n" +
	"sandbox_ip\x18\x05 \x01(\tR\tsandboxIp\x12F\n" +
	"\rport_mappings\x18\x06 \x03(\v2!.network_agent.api.v1.PortMappingR\fportMappings\"\x86\x01\n" +
	"\vPortMapping\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\rR\bhostPort\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\"\x87\x01\n" +
	"\tInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bip_cidrs\x18\x03 \x03(\tR\aipCidrs\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\"d\n" +
	"\x05Route\x12)\n" +
	"\x10destination_cidr\x18\x01 \x01(\tR\x0fdestinationCidr\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"V\n" +
	"\vARPNeighbor\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"\x9a\x01\n" +
	"\rCubeVSContext\x127\n" +
	"\x15allow_internet_access\x18\x01 \x01(\bH\x00R\x13allowInternetAccess\x88\x01\x01\x12\x1b\n" +
	"\tallow_out\x18\x02 \x03(\tR\ballowOut\x12\x19\n" +
	"\bdeny_out\x18\x03 \x03(\tR\adenyOutB\x18\n" +
	"\x16_allow_internet_access2\xf5\x04\n" +
	"\fNetworkAgent\x12h\n" +
	"\rEnsureNetwork\x12*.network_agent.api.v1.EnsureNetworkRequest\x1a+.network_agent.api.v1.EnsureNetworkResponse\x12k\n" +
	"\x0eReleaseNetwork\x12+.network_agent.api.v1.ReleaseNetworkRequest\x1a,.network_agent.api.v1.ReleaseNetworkResponse\x12q\n" +
	"\x10ReconcileNetwork\x12-.network_agent.api.v1.ReconcileNetworkRequest\x1a..network_agent.api.v1.ReconcileNetworkResponse\x12_\n" +
	"\n" +
	"GetNetwork\x12'.network_agent.api.v1.GetNetworkRequest\x1a(.network_agent.api.v1.GetNetworkResponse\x12S\n" +
	"\x06Health\x12#.network_agent.api.v1.HealthRequest\x1a$.network_agent.api.v1.HealthResponse\x12e\n" +
	"\fListNetworks\x12).network_agent.api.v1.ListNetworksRequest\x1a*.network_agent.api.v1.ListNetworksResponseBIZGgithub.com/tencentcloud/CubeSandbox/network-agent/api/v1;networkagentv1b\x06proto3"

var (
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescOnce sync.Once
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescData []byte
)

func file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescGZIP() []byte {
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescOnce.Do(func() {
		file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDesc), len(file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDesc)))
	})
	return file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDescData
}

var file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_goTypes = []any{
	(*EnsureNetworkRequest)(nil),     // 0: network_agent.api.v1.EnsureNetworkRequest
	(*EnsureNetworkResponse)(nil),    // 1: network_agent.api.v1.EnsureNetworkResponse
	(*ReleaseNetworkRequest)(nil),    // 2: network_agent.api.v1.ReleaseNetworkRequest
	(*ReleaseNetworkResponse)(nil),   // 3: network_agent.api.v1.ReleaseNetworkResponse
	(*ReconcileNetworkRequest)(nil),  // 4: network_agent.api.v1.ReconcileNetworkRequest
	(*ReconcileNetworkResponse)(nil), // 5: network_agent.api.v1.ReconcileNetworkResponse
	(*GetNetworkRequest)(nil),        // 6: network_agent.api.v1.GetNetworkRequest
	(*GetNetworkResponse)(nil),       // 7: network_agent.api.v1.GetNetworkResponse
	(*HealthRequest)(nil),            // 8: network_agent.api.v1.HealthRequest
	(*HealthResponse)(nil),           // 9: network_agent.api.v1.HealthResponse
	(*ListNetworksRequest)(nil),      // 10: network_agent.api.v1.ListNetworksRequest
	(*ListNetworksResponse)(nil),     // 11: network_agent.api.v1.ListNetworksResponse
	(*NetworkState)(nil),             // 12: network_agent.api.v1.NetworkState
	(*PortMapping)(nil),              // 13: network_agent.api.v1.PortMapping
	(*Interface)(nil),                // 14: network_agent.api.v1.Interface
	(*Route)(nil),                    // 15: network_agent.api.v1.Route
	(*ARPNeighbor)(nil),              // 16: network_agent.api.v1.ARPNeighbor
	(*CubeVSContext)(nil),            // 17: network_agent.api.v1.CubeVSContext
	nil,                              // 18: network_agent.api.v1.EnsureNetworkRequest.PersistMetadataEntry
	nil,                              // 19: network_agent.api.v1.EnsureNetworkResponse.PersistMetadataEntry
	nil,                              // 20: network_agent.api.v1.ReleaseNetworkRequest.PersistMetadataEntry
	nil,                              // 21: network_agent.api.v1.ReleaseNetworkResponse.PersistMetadataEntry
	nil,                              // 22: network_agent.api.v1.ReconcileNetworkRequest.PersistMetadataEntry
	nil,                              // 23: network_agent.api.v1.ReconcileNetworkResponse.PersistMetadataEntry
	nil,                              // 24: network_agent.api.v1.GetNetworkResponse.PersistMetadataEntry
}
var file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_depIdxs = []int32{
	14, // 0: network_agent.api.v1.EnsureNetworkRequest.interfaces:type_name -> network_agent.api.v1.Interface
	15, // 1: network_agent.api.v1.EnsureNetworkRequest.routes:type_name -> network_agent.api.v1.Route
	16, // 2: network_agent.api.v1.EnsureNetworkRequest.arp_neighbors:type_name -> network_agent.api.v1.ARPNeighbor
	13, // 3: network_agent.api.v1.EnsureNetworkRequest.port_mappings:type_name -> network_agent.api.v1.PortMapping
	18, // 4: network_agent.api.v1.EnsureNetworkRequest.persist_metadata:type_name -> network_agent.api.v1.EnsureNetworkRequest.PersistMetadataEntry
	17, // 5: network_agent.api.v1.EnsureNetworkRequest.cubevs_context:type_name -> network_agent.api.v1.CubeVSContext
	14, // 6: network_agent.api.v1.EnsureNetworkResponse.interfaces:type_name -> network_agent.api.v1.Interface
	15, // 7: network_agent.api.v1.EnsureNetworkResponse.routes:type_name -> network_agent.api.v1.Route
	16, // 8: network_agent.api.v1.EnsureNetworkResponse.arp_neighbors:type_name -> network_agent.api.v1.ARPNeighbor
	13, // 9: network_agent.api.v1.EnsureNetworkResponse.port_mappings:type_name -> network_agent.api.v1.PortMapping
	19, // 10: network_agent.api.v1.EnsureNetworkResponse.persist_metadata:type_name -> network_agent.api.v1.EnsureNetworkResponse.PersistMetadataEntry
	20, // 11: network_agent.api.v1.ReleaseNetworkRequest.persist_metadata:type_name -> network_agent.api.v1.ReleaseNetworkRequest.PersistMetadataEntry
	21, // 12: network_agent.api.v1.ReleaseNetworkResponse.persist_metadata:type_name -> network_agent.api.v1.ReleaseNetworkResponse.PersistMetadataEntry
	14, // 13: network_agent.api.v1.ReconcileNetworkRequest.interfaces:type_name -> network_agent.api.v1.Interface
	15, // 14: network_agent.api.v1.ReconcileNetworkRequest.routes:type_name -> network_agent.api.v1.Route
	16, // 15: network_agent.api.v1.ReconcileNetworkRequest.arp_neighbors:type_name -> network_agent.api.v1.ARPNeighbor
	13, // 16: network_agent.api.v1.ReconcileNetworkRequest.port_mappings:type_name -> network_agent.api.v1.PortMapping
	22, // 17: network_agent.api.v1.ReconcileNetworkRequest.persist_metadata:type_name -> network_agent.api.v1.ReconcileNetworkRequest.PersistMetadataEntry
	17, // 18: network_agent.api.v1.ReconcileNetworkRequest.cubevs_context:type_name -> network_agent.api.v1.CubeVSContext
	14, // 19: network_agent.api.v1.ReconcileNetworkResponse.interfaces:type_name -> network_agent.api.v1.Interface
	15, // 20: network_agent.api.v1.ReconcileNetworkResponse.routes:type_name -> network_agent.api.v1.Route
	16, // 21: network_agent.api.v1.ReconcileNetworkResponse.arp_neighbors:type_name -> network_agent.api.v1.ARPNeighbor
	13, // 22: network_agent.api.v1.ReconcileNetworkResponse.port_mappings:type_name -> network_agent.api.v1.PortMapping
	23, // 23: network_agent.api.v1.ReconcileNetworkResponse.persist_metadata:type_name -> network_agent.api.v1.ReconcileNetworkResponse.PersistMetadataEntry
	14, // 24: network_agent.api.v1.GetNetworkResponse.interfaces:type_name -> network_agent.api.v1.Interface
	15, // 25: network_agent.api.v1.GetNetworkResponse.routes:type_name -> network_agent.api.v1.Route
	16, // 26: network_agent.api.v1.GetNetworkResponse.arp_neighbors:type_name -> network_agent.api.v1.ARPNeighbor
	13, // 27: network_agent.api.v1.GetNetworkResponse.port_mappings:type_name -> network_agent.api.v1.PortMapping
	24, // 28: network_agent.api.v1.GetNetworkResponse.persist_metadata:type_name -> network_agent.api.v1.GetNetworkResponse.PersistMetadataEntry
	12, // 29: network_agent.api.v1.ListNetworksResponse.networks:type_name -> network_agent.api.v1.NetworkState
	13, // 30: network_agent.api.v1.NetworkState.port_mappings:type_name -> network_agent.api.v1.PortMapping
	0,  // 31: network_agent.api.v1.NetworkAgent.EnsureNetwork:input_type -> network_agent.api.v1.EnsureNetworkRequest
	2,  // 32: network_agent.api.v1.NetworkAgent.ReleaseNetwork:input_type -> network_agent.api.v1.ReleaseNetworkRequest
	4,  // 33: network_agent.api.v1.NetworkAgent.ReconcileNetwork:input_type -> network_agent.api.v1.ReconcileNetworkRequest
	6,  // 34: network_agent.api.v1.NetworkAgent.GetNetwork:input_type -> network_agent.api.v1.GetNetworkRequest
	8,  // 35: network_agent.api.v1.NetworkAgent.Health:input_type -> network_agent.api.v1.HealthRequest
	10, // 36: network_agent.api.v1.NetworkAgent.ListNetworks:input_type -> network_agent.api.v1.ListNetworksRequest
	1,  // 37: network_agent.api.v1.NetworkAgent.EnsureNetwork:output_type -> network_agent.api.v1.EnsureNetworkResponse
	3,  // 38: network_agent.api.v1.NetworkAgent.ReleaseNetwork:output_type -> network_agent.api.v1.ReleaseNetworkResponse
	5,  // 39: network_agent.api.v1.NetworkAgent.ReconcileNetwork:output_type -> network_agent.api.v1.ReconcileNetworkResponse
	7,  // 40: network_agent.api.v1.NetworkAgent.GetNetwork:output_type -> network_agent.api.v1.GetNetworkResponse
	9,  // 41: network_agent.api.v1.NetworkAgent.Health:output_type -> network_agent.api.v1.HealthResponse
	11, // 42: network_agent.api.v1.NetworkAgent.ListNetworks:output_type -> network_agent.api.v1.ListNetworksResponse
	37, // [37:43] is the sub-list for method output_type
	31, // [31:37] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_init() }
func file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_init() {
	if File_Cubelet_pkg_networkagentclient_pb_network_agent_proto != nil {
		return
	}
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDesc), len(file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_goTypes,
		DependencyIndexes: file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_depIdxs,
		MessageInfos:      file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_msgTypes,
	}.Build()
	File_Cubelet_pkg_networkagentclient_pb_network_agent_proto = out.File
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_goTypes = nil
	file_Cubelet_pkg_networkagentclient_pb_network_agent_proto_depIdxs = nil
}
